"""add corrections table

Revision ID: 811222534166
Revises: 25476217ad13
Create Date: 2026-06-17 13:46:41.045906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811222534166'
down_revision: Union[str, Sequence[str], None] = '25476217ad13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('corrected', sa.Text(), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_action_type'), 'corrections', ['action_type'], unique=False)
    op.create_index(op.f('ix_corrections_id'), 'corrections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrections_id'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_action_type'), table_name='corrections')
    op.drop_table('corrections')
    # ### end Alembic commands ###
